version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - <project_name>-sync:/var/www/html:nocopy
      - ./.docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - <project_name>-network

  phpfpm:
    build:
      context: .
      dockerfile: ./.docker/phpfpm/Dockerfile
    networks:
      - <project_name>-network

  mariadb:
    image: mariadb
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
     - 6379:6379
    networks:
      - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local